---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    channel: "channel-2"
    config: .eslintrc.codeclimate
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.jsx"
exclude_paths:
- "tests/"
- "spec/"
- "**.spec.js"
- "**.flow"
